model:
  model_type:       simclr
  model_path:       /content/SIMCLR_ssl_resnet18_pretrained_full.ckpt
  image_size:       256
  embedding_size:   512

data:
  data_path:        /content/Dataset

test:
  metric_csv_path: /content/metrics.csv
  prob_csv_path:   /content/prob.csv
  test_path:       /content/TestData
  class:           airplane
  evaluation_path: /content/Evaluation_Data

nn:
  ref_img_path:     /content/RESISC45/airplane/airplane_001.jpg
  swipe_url:
  simulate_label:   True
  unlabled_path:    /content/runtime/swipe/unlabeled
  labeled_path:     /content/runtime/swipe/labeled
  positive_path:    /content/runtime/swipe/labeled/positive
  negative_path:    /content/runtime/swipe/labeled/negative
  unsure_path:      /content/runtime/swipe/unsure

annoy:
    num_nodes:      512
    num_trees:      50
    annoy_path:     /content/runtime/NN_local/annoy_file

TrainModels:
  dummy_dataset:    /content/dummy
  config_path:      /content/AL_testing/ActiveLabeler-main/ActiveLabelerModels/config.yaml

ActiveLabeler:
  sample_size:      120
  sampling_strategy: "gaussian" #"uncertainty_balanced" # "random" #"uncertainty"

AL_main:
  newly_labled_path:  /content/new_label
  archive_path:       /content/runtime/swipe/archive
  nn:                 0
  n_closest:          5
  al_folder:          /content/runtime/AL

Continuation:
 nn: 0
 seed_data_path: /content/seed_dataset


